### PR TITLE
Ignore case of authType

### PR DESCRIPTION
**Pull request by mediumTaj**
This pull request ignores the case of authType coming from external configuration

### CODE REVIEW

**Comment by mediumTaj** [comment]
Sorry @padamstx - one more change... forgot about this issue. We should be good for your changes after this is merged

**Review by padamstx — APPROVED** [review]
It's hard to believe there were not testcase changes to go along with the functional change, @mediumtaj :)

**Comment by mediumTaj** [comment]
sorry, added tests for these ;)

**Pull request merged**
