### PR TITLE
Avoid multiple auth calls

### PR DESCRIPTION
**Pull request by mediumTaj**
This pull request addresses an issue where a client was seeing calls to get iam token on each service call. This boiled down to comparing time in seconds vs milliseconds.

### CODE REVIEW

**Review by padamstx — APPROVED** [review]
LGTM;

**Comment by padamstx** [comment]
If you based your .NET core implementation on the Go or Java core, does that mean we need to fix those implementations too?  :)

**Review by lpatino10 — APPROVED** [review]

**Comment by mediumTaj** [comment]
I think Logan has a pr for java core in the works. I think the java implementation had already changed since I converted it over to .net :)

**Pull request merged**
