### PR TITLE
Enterprise proxy support

### PR DESCRIPTION
**Pull request by darkmatter2222**
Support for enterprise proxy as discussed here: https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/452

Tested outside enterprise proxy
Tested inside enterprise proxy

### CODE REVIEW

**Comment by darkmatter2222** [comment]
This [here](https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/453) will need to be done with this [here](https://github.com/IBM/dotnet-sdk-core/pull/40) Sorry. Proxy required on initialization of httpClient.

**Comment by mediumTaj** [comment]
Thanks for the PR! @kevinkowa can you review the PR here and in the .NET sdk repo and test? If we're looking good please create an issue to add this to the generator for the rest of the services.

**Comment by kevinkowa** [comment]
LGTM! It's working with & without a proxy!

**Review by kevinkowa — APPROVED** [review]

**Pull request merged**
